# Generated by Django 6.0.5 on 2026-05-07 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('country', models.CharField(help_text='Produktionsland', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('car_type', models.CharField(choices=[('Limousine', 'Limousine'), ('SUV', 'SUV'), ('Kombi', 'Kombi'), ('Coupé', 'Coupé'), ('Cabrio', 'Cabrio'), ('Hatchback', 'Hatchback'), ('Pickup', 'Pickup'), ('Sportwagen', 'Supersportwagen'), ('Van', 'Van')], max_length=50)),
                ('engine_type', models.CharField(choices=[('Benzin', 'Benzin'), ('Diesel', 'Diesel'), ('Hybrid', 'Hybrid'), ('Elektro', 'Elektro'), ('Wasserstoff', 'Wasserstoff')], max_length=50)),
                ('transmission', models.CharField(choices=[('Manuell', 'Manuell'), ('Automatik', 'Automatik'), ('Doppelkupplung', 'Doppelkupplung'), ('CVT', 'CVT')], max_length=50)),
                ('drive_type', models.CharField(choices=[('Front', 'Frontantrieb'), ('Heck', 'Heckantrieb'), ('Allrad', 'Allrad')], max_length=50)),
                ('hp', models.IntegerField(help_text='PS')),
                ('kw', models.IntegerField(blank=True, help_text='kW', null=True)),
                ('torque', models.IntegerField(help_text='Drehmoment in Nm')),
                ('top_speed', models.IntegerField(help_text='km/h')),
                ('acceleration', models.FloatField(help_text='0-100 km/h in Sekunden')),
                ('consumption', models.FloatField(help_text='l/100 km oder kWh/100 km')),
                ('range', models.IntegerField(blank=True, help_text='Reichweite in km', null=True)),
                ('capacity', models.FloatField(help_text='Tank (Liter) oder Batterie (kWh)')),
                ('length', models.IntegerField(help_text='Länge in mm')),
                ('width', models.IntegerField(help_text='Breite in mm')),
                ('height', models.IntegerField(help_text='Höhe in mm')),
                ('trunk_volume', models.IntegerField(help_text='Kofferraum in Liter')),
                ('weight', models.IntegerField(help_text='Leergewicht in kg')),
                ('seats', models.IntegerField()),
                ('safety_features', models.TextField(help_text='z.B. ABS, 6 Airbags, ESP')),
                ('assistance_systems', models.TextField(help_text='z.B. Abstandstempomat, Spurhalteassistent')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='car_app.manufacturer')),
            ],
        ),
    ]
